### ISSUE TITLE
correct (onError)

### ISSUE THREAD

**Issue by Modarresi** [qontu/ngx-inline-editor#106]
Thanks for your useful Component.
please correct this on your README.md
(onError)="myHandleError"  ==> (onError)="myHandleError()"

**Comment by xxxtonixxx** [comment]
Thank you @Modarresi! :smile: 

Could you send us a PR with that correction? :sweat_smile:

**Comment by Modarresi** [comment]
sorry
I m new. what means PR

**Comment by xxxtonixxx** [comment]
@Modarresi, a Pull Request is a contribution to the code base. A better definition could be [this](https://help.github.com/articles/about-pull-requests/) :+1:
