### ISSUE TITLE
Unexpected token in build - .Net Core

### ISSUE THREAD

**Issue by jbalessandro** [qontu/ngx-inline-editor#115]
I have the following error during dotnet publish:

-----------------
ERROR in ./$$_gendir/~/@qontu/ngx-inline-editor/ngx-inline-editor.ngfactory.ts
      Module parse failed: D:\NovaMesaCredito\$$_gendir\node_modules\@qontu\ngx-inline-editor\ngx-inline-editor.ngfactory.ts Unexpected token (13:40)
      You may need an appropriate loader to handle this file type.
      | import * as i2 from '@angular/common';
      | import * as i3 from '@angular/forms';
      | export const InlineEditorModuleNgFactory:i0.NgModuleFactory<i1.InlineEditorModule> = i0.╔Ácmf(i1.InlineEditorModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/mesa/perfil/perfil-cliente/perfil-cliente.component.ngfactory.ts 10:0-119
       @ ./$$_gendir/ClientApp/app/components/mesa/perfil/perfil/perfil.component.ngfactory.ts
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

-----------------

I've run npm i @qontu/ngx-inline-editor --save 

Tks for all helps.

**Comment by jbalessandro** [comment]
I found the solution:

Just remove  "include: /ClientApp/"

before:
                // { test: /\.ts$/, include: /ClientApp/, use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader'] : '@ngtools/webpack' },

after:
                { test: /\.ts$/, use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader'] : '@ngtools/webpack' },

**Comment by jbalessandro** [comment]
Solved

**Comment by xxxtonixxx** [comment]
Thanks for your feedback! :+1:
