### ISSUE TITLE
Enable editing on double click

### ISSUE THREAD

**Issue by venkydeshmukh** [qontu/ngx-inline-editor#117]
I am trying to implement ngx-inline-editor in tab. I have HTML form with multiple tabs.
When user double clicks on the tab, tab name should become editable. ngx-inline-editor (which is my natural choice for inline editing) displays textbox for editing, as soon as user clicks on tab. 

Is it possible to implement double click functionality for enabling editing also?

**Comment by KeithGillette** [comment]
Set `[editOnClick]="false"` and then add an Angular `(dblclick)` handler to invoke the inline editor programmatically via its `edit({editing: true, focus: true, select: true})` method. You can get a reference to it in the component controller using `@ViewChild` or `@ViewChildren`.

**Comment by venkydeshmukh** [comment]
Thanks Keith,
It works as expected.

**Comment by San13** [comment]
Hi Sir, 
Can u provide some working example for beginner level like me ?

**Comment by sric88** [comment]
I tried below code

`import { InlineEditorComponent } from '@qontu/ngx-inline-editor';`

`@ViewChild('InlineEditorComponent') private _child: InlineEditorComponent;`

```
myHandleError(){
this._child.edit({ editing: true, focus: true, select: true });
}
```

But getting error "Cannot read property 'edit' of undefined"

Can you please help me where I'm doing mistake

**Comment by KeithGillette** [comment]
@sric88: Unless you have given your `<inline-editor>` element id of `InlineEditorComponent` in the template your code will fail, as the `@ViewChild()` decorator expects a string argument to match a template element id. If the argument is a component class token, it will pick up the first instance of that component in the template. So just take the single-quotes off:
`@ViewChild(InlineEditorComponent) private _child: InlineEditorComponent;`

**Comment by sric88** [comment]
Thanks Keith. It works fine 👍

**Comment by jovanica7** [comment]
Hi, is it possible to keep focus on input, when an error is occurred? So, when I call (onError)="myHandleError()" to put a similar code as above in it?

Example:
myHandleError(){
//some code
this._child.edit({ editing: true, focus: true, select: true });
}

I tried this, but nothing happens, I am not sure what I need to pass as a parameter in html/ts component. When I call console.log(this._child); current element is displayed, which is good. But unfortunately editor closes.
