### ISSUE TITLE
The Tick and X buttons looks like blank hypons

### ISSUE THREAD

**Issue by swethaAllam** [qontu/ngx-inline-editor#119]
![screen shot 2018-01-23 at 12 28 17 pm](https://user-images.githubusercontent.com/27245885/35299052-eca294c8-0038-11e8-968d-670eda990aeb.png)

What is that I am missing? I am using this with angular2-collapsible library

**Comment by Caballerog** [comment]
Hi @swethaAllam,

I think that would be that fontawesome.css is missing.

**Comment by swethaAllam** [comment]
@Caballerog Thank you for the early response. Can you please shed some light on how I can get that css?

**Comment by swethaAllam** [comment]
I got it to work. thank you. I followed https://stackoverflow.com/questions/38796541/how-to-add-font-awesome-to-angular-2-cli-project
