### ISSUE TITLE
pass arguments to fnErrorPattern and fnErrorLength ?

### ISSUE THREAD

**Issue by sinegovsky-ivan** [qontu/ngx-inline-editor#22]

**Comment by xxxtonixxx** [comment]
@sinegovsky-ivan arguments? which ones?

**Comment by xxxtonixxx** [comment]
`fnErrorPattern` and `fnErrorLength` have been deprecated. You can use the `onError` output event:
```typescript
<inline-editor ... (onError)="myHandleError($event)" ...></inline-editor>
```
`$event` is a parameter of type `InlineEditorError[] -> { type: string, message: string }[]`
