### ISSUE TITLE
Trigger manually

### ISSUE THREAD

**Issue by elmartino** [qontu/ngx-inline-editor#24]
Is there an option to trigger the edit manually from another button for example?
Thanks for your reply!

**Comment by Caballerog** [comment]
I have not yet developed it, but I can included this feature in the roadmap.

**Comment by elmartino** [comment]
that would be great thanks!

**Comment by xxxtonixxx** [comment]
This should be fixed in the last version (`0.2.0-alpha.0`). With the change of name, you should do an `npm i @qontu/ngx-inline-editor` and update your imports 👍
