### ISSUE TITLE
"Empty" text value does not appear when min=0 and the user validates and empty value

### ISSUE THREAD

**Issue by Eolan** [qontu/ngx-inline-editor#31]
When min=0 is declared and the user validate empty content, the 'empty' text doesn't appear and the component is not selectable because not visible anymore.

**Comment by xxxtonixxx** [comment]
Does it happen using an input number or text? And can you test it with the last version `0.2.0-alpha.0`?

Thanks for reporting! 👍

**Comment by pedrollo** [comment]
@xxxtonixxx It happens also in **0.2.0-alpha.11** - number & text input.

**Comment by xxxtonixxx** [comment]
Hmmm, I will investigate it, thanks @pedrollo :+1:

**Comment by pedrollo** [comment]
@xxxtonixxx Tried to reproduce with **0.2.0-alpha.12** but couldn't. I assume it was an implementation error on our side or the bug was fixed. Checked on a fresh angular project: *text* and *number* type inputs.
