### ISSUE TITLE
custom button size

### ISSUE THREAD

**Issue by apriyadarshi38** [qontu/ngx-inline-editor#32]
Hi can i get control to change button property such as padding ,width etc???????

**Comment by sh977218** [comment]
There is default styles for all html elements. You can add customized styles in component to overwrite them.

**Comment by Caballerog** [comment]
I just to update the new version in which you would use your own styles.

The className of the buttons are the classical naming of bootstrap (btn btn-primary btn-xs and bnt-danger).

This feature is in the version 0.1.1-alpha.20
