### ISSUE TITLE
Empty option does not work with text area

### ISSUE THREAD

**Issue by otusweb** [qontu/ngx-inline-editor#42]
I created a text entry:
` <inline-editor type="text" empty="test" [(ngModel)]="slide.tweet" (onSave)="saveEditable($event)" name="tweetText" size="140"></inline-editor>`

But the empty string is not shown when slide.tweet is an empty string ("") as opposed to null

commit #4877aed5f727ea2b14a85fc2e2e55eed0f865d28

**Comment by xxxtonixxx** [comment]
I have tested your code on `0.2.0-alpha.0` and it works. If it does not work yet, please, reopen! 😉 

Thanks for reporting 👍
