### ISSUE TITLE
Input text size should be "0"

### ISSUE THREAD

**Issue by Caballerog** [qontu/ngx-inline-editor#69]
At the moment the default value for input text size is 8, this is a problem when you wish use Bootstrap or any framework to design your component.

If the default value is -1 or 0, the component use the class assign to define the size of the input. Futhermore, in the configuration object you would define your own size in the case that you need define this value.

**Comment by Caballerog** [comment]
The default value -1 or 0, really provoke that the browser determine the input's size.

So, another solution should be used.

**Comment by Caballerog** [comment]
I've found a temporal solution for this issue.

In your .scss you would use the following rules:
```
#inlineEditWrapper {
  width: 100%;

  .c-inline-editor {
    width: 100%;

    inline-editor-text {
      width: 100%;

      input {
        width: 100%;
      }
    }
    inline-editor-select {
      width: 100%;

      select {
        width: 100%;
      }
    }
  }
}
```
So, your input type text and select using the 100% of the parent container. If you want more control your would use the angular component like a selector (+1 in the specificity):

```
myComponent #inlineEditWrapper {
  width: 100%;

  .c-inline-editor {
    width: 100%;

    inline-editor-text {
      width: 100%;

      input {
        width: 100%;
      }
    }
    inline-editor-select {
      width: 100%;

      select {
        width: 100%;
      }
    }
  }
}
```

**Comment by KeithGillette** [comment]
I think there's also a `form-group` child element between the `c-inline-editor` and `inline-editor-text` elements that may need to be set to 100%, as well.

Can you provide a working Plunker of a dynamically-sized inline-editor, @Caballerog?

I'm struggling to get the editor to size dynamically inline with other items. We want to display an inline editor inside a parent element that sizes dynamically and adjusts its width to the container size minus left & right elements, per this [Plunker example](https://plnkr.co/edit/UC69ey?p=preview).

Thanks in advance for any pointers!

**Comment by Caballerog** [comment]
Hi @KeithGillette,

The main problem in your Plunker example is the class ".c-inline-editor.inlineEditForm input" from "bootstrap.css" line 32, in which . the width is "auto". The style "input" don't overwrite this class due to is less specificity that the rule which exists in "bootstrap.css".

I've remove my bootstrap.css example from the index.html in your Plunker and I get the 100% width like you want.

**Comment by KeithGillette** [comment]
Thanks for the fast reply, @Caballerog!

I see the issue you are describing, but still can't get it working even omitting the external styles. I updated the Plunker to not load the external stylesheets but when the inline-editor is invoked, the input is still a fixed width, even though inspecting the CSS shows it inheriting `width: 100%` from the `inline-editor`.

The CSS selectors I'm seeing when inspecting don't match entirely with those that you [posted previously in this thread](https://github.com/qontu/ngx-inline-editor/issues/69#issuecomment-308985046), so I'm not sure exactly what selectors to use to get the `input` to fill 100% of its parent…
