### ISSUE TITLE
Externally Trigger Editing Mode with an input

### ISSUE THREAD

**Issue by jongunter** [qontu/ngx-inline-editor#74]
It would be useful if one could trigger editing from an input. For example:
```
<inline-editor [(ngModel)]="username" [isEditing]="editButtonPressed"></inline-editor>
<button (click)="editButtonPressed = true">Edit Username</button>
```

**Comment by xxxtonixxx** [comment]
Hi @jongunter, you can do it 👍, simply:

```typescript
<inline-editor #myInlineEditor [(ngModel)]="username"></inline-editor>
<button (click)="myInlineEditor.edit({ editing: true })">Edit Username</button>
```

😄

**Comment by Emmpa** [comment]
That worked great for me ... except that if I click cancel, then it shows [object Object] instead of the original text. Clicking on the element normally does not give that problem though.

```html
<button (click)="organization.edit({ editing: true })">
<inline-editor #organization type="text" [(ngModel)]="org.name" (onSave)="saveOrg()" class="org-name" size="20"></inline-editor>
```

**Comment by xxxtonixxx** [comment]
@Emmpa I can not reproduce your problem using your code. Please, provide me a complete demo or more concrete steps 👍 And what version of ngx-inline-editor are you using?

**Comment by Emmpa** [comment]
Hmm... I think I was using an older version of the inline-editor. I updated the version and everything is working correctly now. Thank you!!

**Comment by xxxtonixxx** [comment]
Ok @Emmpa Your welcome 😉
