### ISSUE TITLE
Validating after onSave

### ISSUE THREAD

**Issue by tom-b-wright** [qontu/ngx-inline-editor#77]
I am looking for a way to implement this scenario: a phone number field gets edited and when I click save, the (onSave) event is triggered; the back-end is invoked and it rejects the phone number as being duplicate, invalid, wrong country etc. The problem is that I can't signal to the inline-editor that, in fact, the value is wrong and an error message should be displayed. The editor goes back to 'displaying' state.
Do you have a solution/workaround for this scenario?

Thanks for your precious time!

**Comment by xxxtonixxx** [comment]
Hi! Yeah, a workaround for this scenario could be:

- Template
```typescript
<inline-editor type="text" [(ngModel)]="phone" [onlyValue]="false" (onSave)="saveItOrRestoreIt($event)" (onEdit)="savePrevValue($event)"></inline-editor>
```

- Component
```typescript
prevPhone: string;
// Save your value when edit mode was triggered
savePrevValue(event: InlineEditorEvent) {
    this.prevPhone = event.state.value;
}

saveItOrRestoreIt(event: InlineEditorEvent) {
   const value = event.state.value;

  // To do your http
   this.http.post({..., data: value}).subscribe(
        () => console.log("Ok. Phone saved"),
        // Rollback your phone in inline-editor
        () => event.save({ statte: { ...event.state, value: this.prevPhone})
   );
}
```

**Comment by tom-b-wright** [comment]
It works indeed!
Thank you Toni!
