### ISSUE TITLE
`onSave` method called twice if both `saveOnBlur` and `saveOnEnter` attributes set to `true`

### ISSUE THREAD

**Issue by KeithGillette** [qontu/ngx-inline-editor#83]
We are using `ngx-inline-editor` with `hideButtons` set to true and want to have the input text value saved either when the user presses Enter or clicks outside the input, causing the the input to blur, so we have set both `saveOnBlur` and `saveOnEnter` to `true`. This causes the method bound to `onSave` to be called twice if the user presses `Enter`, perhaps because that action causes the input to blur. Since the same user action is triggering the save, I think that the `onSave` method should only be invoked once.

**Comment by xxxtonixxx** [comment]
I understand your problem and you are right! `onSave` should only trigger once

Thanks for your reporting 👍

**Comment by xxxtonixxx** [comment]
It is fixed in `0.2.0-alpha.9` 😄
