### ISSUE TITLE
how to config ngx-inline-editor, so that it does not start a new line

### ISSUE THREAD

**Issue by zhaochy1990** [qontu/ngx-inline-editor#84]
ngx-inline-editor always starts a new line

for instance, the following html,

```
aaaaaa<inline-editor type="text" [(ngModel)]="var1" name="editableText1"></inline-editor>bbbbbbb
```

I want it to be rendered as 
```
aaaaaa[inline-editor]bbbbbbb
```

but infact it is
```
aaaaaa
[inline-editor]
bbbbbb
```

how to config the inline-editor, so that it won't start from a new line?

**Comment by xxxtonixxx** [comment]
Hi @zhaochy1990 that behavior is already done and it is the default behavior. Please, update your `ngx-inline-editor` version to the latest 👍 

Here you have a simple demo https://embed.plnkr.co/Bq2pVG14oyEJrogsNmeS/

If it doesn't resolve your problem, please, reopen this issue 😉

**Comment by zhaochy1990** [comment]
is the latest version 0.2.0-alpha.6 ?

**Comment by zhaochy1990** [comment]
yeah, it works, thank you.

**Comment by zhaochy1990** [comment]
@xxxtonixxx  the `type="text"` and `type="textarea"` component will not be rendered several days ago, please visit your demo. `password` and `select` is ok, need fix.
https://embed.plnkr.co/Bq2pVG14oyEJrogsNmeS/
