### ISSUE TITLE
ERROR TypeError: this.onChange is not a function

### ISSUE THREAD

**Issue by ahmedtaaw** [qontu/ngx-inline-editor#87]
> ERROR TypeError: this.onChange is not a function

at this line
`<inline-editor placeholder="Email" type="text" formControlName="newEmail"></inline-editor>`
in this project 
[https://github.com/ahmedtaaw/angular-reactive-form-control-dynamic-ngfor-json](https://github.com/ahmedtaaw/angular-reactive-form-control-dynamic-ngfor-json)
under 

> ngx-inline-editor branch

**Comment by xxxtonixxx** [comment]
I have seen your demo and I'm trying it. Thanks for it!

You are using an outdated version. Please update to `@qontu/ngx-inline-editor` and that error will go away. However, I have been another error... I will investigate it 😉

**Comment by ahmedtaaw** [comment]
Thanks for reply, 
yes I see now this error

> Uncaught Error: Unexpected directive 'InlineEditorComponent' imported by the module 'AppModule'. Please add a @NgModule annotation.

**Comment by xxxtonixxx** [comment]
Hmmm, I did not refer to that error. I did not get that error 😕

**Comment by ahmedtaaw** [comment]
yes, it was another error forget this. 
no errors now but I can't see the values unless I press on the field to edit, I only can see the value on edit mode of each field.
you can find it here
[https://github.com/ahmedtaaw/angular-reactive-form-control-dynamic-ngfor-json/tree/ngx-inline-editor](https://github.com/ahmedtaaw/angular-reactive-form-control-dynamic-ngfor-json/tree/ngx-inline-editor)

Thanks @xxxtonixxx for replies 👍

**Comment by xxxtonixxx** [comment]
Hi @ahmedtaaw, I just have open a new PR to resolve that problems https://github.com/qontu/ngx-inline-editor/pull/88

I have been testing using your demo (thanks 😄). I'm going to publish a new version and could you test it in depth? I will appreciate a lot your feedback 👍

**Comment by xxxtonixxx** [comment]
You can update to version `0.2.0-alpha.10` 😉

**Comment by ahmedtaaw** [comment]
issue solved thanks @xxxtonixxx  👍  😄 🎆
