### ISSUE TITLE
"Error: Uncaught (in promise): TypeError: Cannot read property 'length' of null" error thrown when using <inline-editor type="textarea" when [(ngModel)]="null"

### ISSUE THREAD

**Issue by jmorganmartin** [qontu/ngx-inline-editor#92]
The error is fairly self-explanatory. Using version 0.2.0-alpha.11.

Here is my code:

```
<inline-editor type="textarea" [(ngModel)]="booking.description" (onSave)="updateBookingDescription($event)" cols="35" placeholder="Add Notes Here"></inline-editor>
```

If `booking.description` is `null`, triggers the error:

```
Error: Uncaught (in promise): TypeError: Cannot read property 'length' of null
```

The workaround is to write a quick check to prevent passing a variable that might be `null` (an empty string, `''`, is fine).  I believe this issue is new to one of the recent updates.

Triggered in ngx-inline-editor.es5.js (line 235):

```        if (this.canTestLength(this.config)) {
            var _a = this.config, min = _a.min, max = _a.max;
            var /** @type {?} */ length = this.isNumeric ? Number(value) : value.length;
```
If `value` is `null`, `value.length` triggers this error.

**Comment by xxxtonixxx** [comment]
Hi @jmorganmartin, thanks for your reporting and help! 👍 

Yeah, it seems easy to fix. I will fix it when I have time (maybe, next weekend), however if you want help us, you could open a PR 😉

**Comment by jmorganmartin** [comment]
@xxxtonixxx I'm working on it right now. Ran into a separate issue trying to build.

**Comment by jmorganmartin** [comment]
https://github.com/qontu/ngx-inline-editor/pull/95

**Comment by xxxtonixxx** [comment]
Fixed in https://github.com/qontu/ngx-inline-editor/pull/95
