### ISSUE TITLE
Cannot build (rollup version conflicts). "Error: Unexpected key 'moduleName' found"

### ISSUE THREAD

**Issue by jmorganmartin** [qontu/ngx-inline-editor#94]
`"gulp-rollup": "^2.14.0"` currently resolves to `gulp-rollup@2.15.0` which requires `rollup@0.49.3` which conflicts with the `"rollup" : "0.47.2"` required in package.json.

If `gulp-rollup@2.15.0` is installed (with its `rollup@0.49.3` dependency), the `npm run build` will throw this error:

**ngx-inline-editor\node_modules\gulp-rollup\node_modules\rollup\dist\rollup.js:171**
```
Error: Unexpected key 'moduleName' found, expected one of: acorn, amd, banner, cache, context, entry, exports, extend, external, file, footer, format, globals, indent, input, interop, intro, legacy, moduleContext, name, noConflict, onwarn, output, outro, paths, plugins, preferConst, pureExternalModules, sourcemap, sourcemapFile, strict, targets, treeshake, watch
```

Solution: restrict gulp-rollup version to 2.14.0 in package.json:
```
- "gulp-rollup": "^2.14.0",
+ "gulp-rollup": "2.14.0",
```

**Comment by jmorganmartin** [comment]
https://github.com/qontu/ngx-inline-editor/pull/95

**Comment by xxxtonixxx** [comment]
Thank you! 👍

**Comment by xxxtonixxx** [comment]
Fixed in https://github.com/qontu/ngx-inline-editor/pull/95
